- name: test cmd from win_command module
  hosts: all
  tasks:
    - name: copy files to windows server 1
      win_copy:
       src: files/lgpo
       dest: C:\

    - name: copy files admx1
      win_copy:
       src: files/policies2016/MSS-legacy.admx
       dest: C:\windows\PolicyDefinitions\


    - name: copy files admx2
      win_copy:
       src: files/policies2016/SecGuide.admx
       dest: C:\windows\PolicyDefinitions\


    - name: copy files adml1
      win_copy:
       src: files/policies2016/SecGuide.adml
       dest: C:\windows\PolicyDefinitions\en-US\

  
    - name: copy files adml2
      win_copy:
       src: files/policies2016/MSS-legacy.adml
       dest: C:\windows\PolicyDefinitions\en-US\