- name: test cmd from win_command module
  hosts: all
  tasks:
    - name: copy files to windows server 
      win_copy:
       src: /lgpo2019
       dest: C:\
       src: /polfiles/*.admx
       dest: c:\windows\PolicyDefinitions
       src: /polfiles/*.adml
       dest: c:\windows\PolicyDefinitions\en-US
       remote_src: true
